version: "3"
services:
  db:
    build: ./build/db
    platform: linux/x86_64
    volumes:
      - db-store:/var/lib/mysql
    environment:
      MYSQL_DATABASE: test-db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
  app:
    build:
      context: .
      dockerfile: ./build/rest/Dockerfile
    tty: true
    volumes:
      - ./cmd:/go/src/app
    ports:
      - "3000"
  nginx:
    build: ./build/nginx
    ports:
      - "80:80"
    depends_on:
      - "app"

volumes:
  db-store: